export const vouchers = [
        {
            logo: 'VOUCHER XTRA',
            category: 'Toàn Ngành Hàng',
            discount: 'Giảm 15% Giảm tối đa ₫100k',
            condition: 'Đơn Tối Thiểu ₫120k',
            time: 'Hiệu lực sau: 2 ngày',
            used: '×5',
            button: 'Dùng Sau',
        },
        {
            logo: 'VOUCHER XTRA',
            category: 'Thời Trang',
            discount: 'Giảm 12% Giảm tối đa ₫25k',
            condition: 'Đơn Tối Thiểu ₫99k',
            time: 'Hiệu lực sau: 2 ngày',
            used: '×3',
            button: 'Dùng Sau',
        },
        {
            logo: 'SHOPEE',
            category: 'SHOPEE',
            discount: 'Giảm 15% Giảm tối đa ₫150k',
            condition: 'Đơn Tối Thiểu ₫750k',
            time: 'Hiệu lực sau: 1 ngày',
            used: '×2',
            button: 'Dùng Sau',
        },
        {
            logo: 'SHOPEE',
            category: 'SHOPEE',
            discount: 'Giảm 8% Giảm tối đa ₫200k',
            condition: 'Đơn Tối Thiểu ₫200k',
            time: 'Hiệu lực sau: 7 giờ',
            used: '×3',
            button: 'Dùng Sau',
        },
        {
            logo: 'VOUCHER XTRA',
            category: 'Toàn Ngành Hàng',
            discount: 'Giảm 12% Giảm tối đa ₫150k',
            condition: 'Đơn Tối Thiểu ₫500k',
            time: 'Hiệu lực sau: 2 ngày',
            used: '×5',
            button: 'Dùng Sau',
        },
        {
            logo: 'SHOPEE',
            category: 'SHOPEE',
            discount: 'Giảm 15% Giảm tối đa ₫150k',
            condition: 'Đơn Tối Thiểu ₫200k',
            time: 'Hiệu lực sau: 7 giờ',
            used: '×5',
            button: 'Dùng Sau',
        },
        {
            logo: 'VOUCHER XTRA',
            category: 'Thời Trang',
            discount: 'Giảm 15% Giảm tối đa ₫50k',
            condition: 'Đơn Tối Thiểu ₫250k',
            time: 'Hiệu lực sau: 2 ngày',
            used: '×3',
            button: 'Dùng Sau',
        },
        {
            logo: 'Thời Trang',
            category: 'Thời Trang',
            discount: 'Giảm 12% Giảm tối đa ₫40k',
            condition: 'Đơn Tối Thiểu ₫250k',
            time: 'Hiệu lực sau: 2 ngày',
            used: '×3',
            button: 'Dùng Sau',
        },
        {
            logo: 'Thời Trang',
            category: 'Thời Trang',
            discount: 'Giảm 10% Giảm tối đa ₫20k',
            condition: 'Đơn Tối Thiểu ₫99k',
            time: 'Hiệu lực sau: 2 ngày',
            used: '×3',
            button: 'Dùng Sau',
        },
        {
            logo: 'SHOPEE',
            category: 'SHOPEE',
            discount: 'Giảm 6% Giảm tối đa ₫100k',
            condition: 'Đơn Tối Thiểu ₫100k',
            time: 'Hiệu lực sau: 2 ngày',
            used: '×10',
            button: 'Dùng Ngay',
        },
    ];